cache_run_c_code = 'Test does not build: Traceback (most recent call last):\n  File "/Users/trentm/tm/node-bunyan/tmp/pycairo-1.10.0/.waf-1.6.4-e3c1e08604b18a10567cfcd2d02eb6e6/waflib/Tools/c_config.py", line 435, in run_c_code\n    bld.compile()\n  File "/Users/trentm/tm/node-bunyan/tmp/pycairo-1.10.0/.waf-1.6.4-e3c1e08604b18a10567cfcd2d02eb6e6/waflib/Build.py", line 192, in compile\n    raise Errors.BuildError(self.producer.error)\nBuildError: Build failed\n -> task failed (exit status 1): \n\t{task 16794288: cprogram test.c.0.o -> testprog}\n[\'/usr/bin/gcc\', \'test.c.0.o\', \'-o\', \'/Users/trentm/tm/node-bunyan/tmp/pycairo-1.10.0/build_directory/.conf_check_be145d2fb86e4c25ca7a1f20372696e6/testbuild/testprog\', \'-L/Library/Frameworks/Python.framework/Versions/2.6/lib\', \'-lpython2.6\', \'-arch\', \'i386\', \'-arch\', \'x86_64\', \'-isysroot\', \'/Developer/SDKs/MacOSX10.5.sdk/\', \'-arch\', \'i386\', \'-arch\', \'x86_64\', \'-isysroot\', \'/Developer/SDKs/MacOSX10.5.sdk/\', \'-isysroot\', \'/Developer/SDKs/MacOSX10.5.sdk/\', \'-arch\', \'i386\', \'-arch\', \'x86_64\']\n'
